# SPDX-License-Identifier: AGPL-3.0-only
import json
import tempfile
import unittest
from pathlib import Path

from tools import sbom

PUBSPEC = """# Generated by pub
packages:
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  local_pkg:
    dependency: "direct main"
    description:
      path: "../x"
    source: path
    version: "0.0.1"
sdks:
  dart: ">=3.0.0 <4.0.0"
"""


class SbomTests(unittest.TestCase):
    def test_rust_licenses_and_unknown(self):
        meta = {"packages": [
            {"name": "serde", "version": "1.0.0", "license": "MIT OR Apache-2.0", "source": "registry"},
            {"name": "ring", "version": "0.17.0", "license": None, "license_file": "LICENSE"},
            {"name": "mystery", "version": "1.0.0", "license": None, "source": None},
        ]}
        report = sbom.build_report(sbom.rust_components(meta))
        info = report["zherodizk"]
        self.assertEqual(info["component_count"], 3)
        self.assertEqual(info["unknown_license_count"], 1)
        self.assertEqual(info["license_summary"]["SEE-LICENSE-FILE"], 1)

    def test_dart_parser_ignores_other_sections(self):
        names = [(c["name"], c["version"]) for c in sbom.dart_components(PUBSPEC)]
        self.assertEqual(names, [("async", "2.11.0"), ("local_pkg", "0.0.1")])

    def test_dart_licences_not_invented(self):
        report = sbom.build_report(sbom.dart_components(PUBSPEC))
        self.assertEqual(report["zherodizk"]["unknown_license_count"], 2)
        self.assertTrue(all(c["licenses"] == [] for c in report["components"]))

    def test_dart_entry_without_version_is_an_error(self):
        with self.assertRaises(ValueError):
            sbom.dart_components("packages:\n  broken:\n    source: hosted\n")

    def test_cli_writes_report_and_rejects_bad_input(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            (root / "m.json").write_text(json.dumps({"packages": [
                {"name": "a", "version": "1", "license": "MIT"}]}), encoding="utf-8")
            out = root / "out/sbom.json"
            self.assertEqual(sbom.main(["--cargo-metadata", str(root / "m.json"), "--output", str(out)]), 0)
            self.assertEqual(json.loads(out.read_text(encoding="utf-8"))["bomFormat"], "CycloneDX")
            (root / "bad.json").write_text("{not json", encoding="utf-8")
            self.assertEqual(sbom.main(["--cargo-metadata", str(root / "bad.json"), "--output", str(out)]), 2)


if __name__ == "__main__":
    unittest.main()
